#!/usr/bin/env php

<?php

define('DS', DIRECTORY_SEPARATOR);
define('ROOT', dirname(__FILE__));

// autoload do Composer 
require ROOT.DS.'vendor'.DS.'autoload.php'; 

// as duas linhas que carregam as variáveis do .env para variáveis de ambiente 
$dotenv = new Dotenv\Dotenv( __DIR__ ); 
$dotenv->load();

require ROOT.DS.'Library'.DS.'Marlon'.DS.'core'.DS.'helpers.php';

$appConfig = require __DIR__.'/config/app.php';
$mailConfig = require __DIR__.'/config/mail.php';

require __DIR__.'/config/autoload.php';

$arguments = $argv;
array_shift($arguments);

if( isset($arguments[0]) )
{
    switch($arguments[0])
    {
        case 'migration':
            $path = __DIR__.'/database/migrations';
            if ($handle = opendir($path)) {
            
                while (false !== ($migration = readdir($handle))) {
            
                    if ($migration != "." && $migration != "..")
                    {
                        require "{$path}/{$migration}";
                        $className = "\\Database\\Migrations\\".preg_replace('/(\.php|[0-9_]{1,})/', '', $migration);
                        
                        if(class_exists($className)){
                            try{
                                $migrate = new $className();
                                $migrate->{$arguments[1]}();
                                echo "the migration '{$migration}' was runned with successful\n";
                            } catch(\PDOException $e){
                                echo $e->getMessage();
                                exit;
                            }
                        }
                    }
                }
            
                closedir($handle);
            }
            break; 
    }
}